### ISSUE TITLE
Update theme

### ISSUE THREAD

**Issue by esebesty** [SU-CompBio/SU-CompBio.github.io#22]
Update to cayman based on popular vote.

**Comment by dBenedek** [comment]
Cayman layout can be set with `theme: jekyll-theme-cayman` in the _config.yml file. When set, the navigation bar (header) disappears.

According to [this](https://github.com/jekyll/jekyll/issues/6351), Cayman has only default layout, so all other pages should use this, and not home.html or page.html layouts.
